PROCEDIMENTOS_BASE = [
    {"nome": "ANGIORM DA AORTA ABDOMINAL", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM DA AORTA TORÁCICA", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM DA AORTA E ILÍACAS", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM ARTERIAL DOS MEMBROS INFERIORES", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM VENOSA DOS MEMBROS INFERIORES", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM ARTERIAL DO ABDOME SUPERIOR", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM ARTERIAL DA PELVE", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM VENOSA DO ABDOME SUPERIOR", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIORM VENOSA DA PELVE", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DE TÓRAX (MEDIASTINO, PULMÃO)", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DO ABDOME SUPERIOR", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DO ABDOME SUPERIOR (QUANTIFICAÇÃO DE FERRO)", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DO ABDOME SUPERIOR (QUANTIFICAÇÃO DE GORDURA)", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DO ABDOME SUPERIOR (PRIMOVIST)", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DO ABDOME SUPERIOR COM ELASTOGRAFIA HEPÁTICA", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "COLANGIORM", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DA PELVE", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DE PRÓSTATA", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DE PELVE (FÍSTULA PERIANAL)", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DE PÊNIS / TESTÍCULO", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "RM DE ASSOALHO PÉLVICO", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "PLACENTA", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "FETAL", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ENTERORM", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "DEFECORM", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "URORM", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ABDOME TOTAL", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "CORPO INTEIRO", "tipo_laudo": "RM", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC ARTERIAL DO TÓRAX (TEP)", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC VENOSA DO TÓRAX", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC VENOSA DO ABDOME SUPERIOR", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC VENOSA DA PELVE", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC DA AORTA TORÁCICA", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC DA AORTA ABDOMINAL", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC DA AORTA E ILÍACAS", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC ARTERIAL DOS MEMBROS INFERIORES", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ANGIOTC VENOSA DOS MEMBROS INFERIORES", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "TC DE ABDOME SUPERIOR", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "TC DA PELVE", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "TC DE ABDOME TOTAL", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "TC LITÍASE URINÁRIA", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "UROTC", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "TC DE TÓRAX", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "ENTEROTC", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "COLONOSCOPIA VIRTUAL", "tipo_laudo": "TC", "especialidade_medica": "MI"},
    {"nome": "USG DE ABDOME TOTAL", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE ABDOME SUPERIOR", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG ELASTOGRAFIA FÍGADO", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE PELVE FEMININA TRANSABDOMINAL", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG TRANSVAGINAL", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE RINS E VIAS URINÁRIAS", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE PRÓSTATA", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE TESTÍCULO", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE PÊNIS", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE PÊNIS COM FARMACOINDUÇÃO", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE TÓRAX", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE PAREDE ABDOMINAL", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DAS REGIÕES INGUINAIS", "tipo_laudo": "USG", "especialidade_medica": "MI"},
    {"nome": "USG DE CERVICAL", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DE TIREÓIDE", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DE PELE", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG TRANSFONTANELA", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DE AXILAS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DE MAMAS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DE ESTRUTURAS SUPERFICIAIS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG OBSTÉTRICO", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG OBSTÉTRICO COM DOPPLER", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG OBSTÉTRICO MORFOLÓGICO (1/2 TRI)", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VEIA CAVA INFERIOR", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VEIAS ILÍACAS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER DA AORTA E ILÍACAS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VEIA PORTA", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER ARTÉRIAS RENAIS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER PÓS TRANSPLANTE", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER DE CARÓTIDAS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VEIAS CERVICAIS", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VENOSO DE MEMBRO INFERIOR", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER ARTERIAL DE MEMBRO INFERIOR", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VENOSO DE MEMBRO SUPERIOR", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER ARTERIAL DE MEMBRO SUPERIOR", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DOPPLER VENOSO DE MEMBROS INFERIORES (VARIZES)", "tipo_laudo": "USG", "especialidade_medica": "USG"},
    {"nome": "USG DE DEDO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DA MÃO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DO PUNHO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE BRAÇO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE COTOVELO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE OMBRO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE QUADRIL", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE PERNA", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE JOELHO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE TORNOZELO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE PÉ", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE MÚSCULO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "USG DE MÚSCULO COM INFILTRAÇÃO", "tipo_laudo": "USG", "especialidade_medica": "MSK"},
    {"nome": "RM GERAL MSK", "tipo_laudo": "RM", "especialidade_medica": "MSK", "pontos_rede_dor": 1.0},
    {"nome": "RM MÃO", "tipo_laudo": "RM", "especialidade_medica": "MSK", "pontos_rede_dor": 1.2},
    {"nome": "RM COLUNA (CERVICAL OU DORSAL OU LOMBAR)", "tipo_laudo": "RM", "especialidade_medica": "MSK", "pontos_rede_dor": 1.1},
    {"nome": "RM PLEXO (BRAQUIAL OU LOMBOSSACRAL)", "tipo_laudo": "RM", "especialidade_medica": "MSK", "pontos_rede_dor": 1.4},
    {"nome": "TC GERAL MSK (OMBRO, BRAÇO, COTOVELO...)", "tipo_laudo": "TC", "especialidade_medica": "MSK", "pontos_rede_dor": 1.0},
    {"nome": "TC COLUNA (CERVICAL OU DORSAL OU LOMBAR)", "tipo_laudo": "TC", "especialidade_medica": "MSK", "pontos_rede_dor": 1.0},
    {"nome": "RM CORAÇÃO (MORFOLÓGICO E FUNCIONAL)", "tipo_laudo": "RM", "especialidade_medica": "CARDIO", "pontos_rede_dor": 1.4},
    {"nome": "RM CORAÇÃO PARA AVALIAÇÃO DE FERRO", "tipo_laudo": "RM", "especialidade_medica": "CARDIO", "pontos_rede_dor": 1.4},
    {"nome": "RM CORAÇÃO + PERFUSÃO + ESTRESSE", "tipo_laudo": "RM", "especialidade_medica": "CARDIO", "pontos_rede_dor": 2.8},
    {"nome": "ANGIOTC CORONÁRIAS", "tipo_laudo": "TC", "especialidade_medica": "CARDIO", "pontos_rede_dor": 1.4},
    {"nome": "SCORE DE CÁLCIO", "tipo_laudo": "TC", "especialidade_medica": "CARDIO", "pontos_rede_dor": 1.0}
]
